### PR TITLE
Merge of new coin DCT (with exchange and rate source)

### PR DESCRIPTION
**Pull request by pnosko**
Hi, 
this pull request contains a new extension - DecentExtension, which adds a new currency - Decent (DCT).
Please review and merge if approved. Thank you.

### CODE REVIEW

**Comment by generalbytes** [comment]
Also svg logo is missing..

**Comment by pnosko** [comment]
Hello, sorry for the confusion, I want to address the concerns:

> - adds a binary dependency (i.e. we can't review it)

the extension is written in Scala, so the simplest solution (i.e. one that doesn't require complete overhaul of your build process to support Scala), is to deploy the extension as a JAR dependency

> - turns off dependency checksum verification for no apparent reason

sorry, that was my mistake, reverted to original state
> - adds a Gradle plugin for no apparent reason

this was added in order to build a fat jar, to circumvent the issue of extension directory not being on the classpath

I want to propose the following solution

- I make the repository with my extension available to you for review

- I remove the shadowJar plugin, and the JAR will be deployed together with all other dependencies in a directory on classpath

Would this be an acceptable solution for you?

**Comment by generalbytes** [comment]
It is completely unacceptable to think that libs/batm-ext-decent.jar will ever make it into our project. It is a 3MB fat jar containing thousands of classes. There is absolutely no way we can get this into our product. I recommend you to commit sources and use gradle scala plugin.

**Comment by pnosko** [comment]
Well, I now understand that the size is an issue for you. No reason to get affronted and snappy over it. It was only a proposal after all. I would appreciate if we could communicate in a civilized manner over this. Thank you for your recommendation.

**Comment by generalbytes** [comment]
It is not matter of size. It is a security issue. How can we make sure that your jar doesn't contain any malicious code when it contains so many binary files? Only way is that we do source code review. That is why we require people to submit source code not a binary blobs.

**Comment by pnosko** [comment]
Thanks for the clarification.

**Comment by rpanak-generalbytes** [comment]
Closing this because of inactivity. Feel free to reopen if needed.

**Pull request closed without merging**
