### PR TITLE
Adds DV Chain Exchange

### PR DESCRIPTION
**Pull request by ztnark**
Backport of DV Chain Exchange from XChange

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
@ztnark Sorry for taking so long to review the code, but we managed to speed up the XChange update, so I deliberately postponed this review. I've just merged the update part for this repository. Can you please implement your changes on top of the newest XChange? I guess you'll be able to get rid of many classes.

**Comment by rpanak-generalbytes** [comment]
One more thing. Instead of changing this PR, create a different one and keep this open. We've encountered some problems with the XChange update in the private part of our repo, so it's better to keep the current version of the PR as a backup.

**Comment by ztnark** [comment]
I'm also having an issue with the new version. It seems com.generalbytes.batm.common.currencies.FiatCurrency can't be resolved..?

**Comment by rpanak-generalbytes** [comment]
It's there in the source code (https://github.com/GENERALBYTESCOM/batm_public/blob/master/currencies/src/main/java/com/generalbytes/batm/common/currencies/FiatCurrency.java). It's in a new module we created. If you're using IntelliJ, you'll have to synchronize the project in the Gradle tool windows so that the Gradle changes are reflected in your IntelliJ project. In Eclipse I guess there should be a similar functionality. If not, you can reimport the project from the Gradle files.

**Comment by ztnark** [comment]
Opened https://github.com/GENERALBYTESCOM/batm_public/pull/173 using xchange 4.3.15

**Comment by rpanak-generalbytes** [comment]
Closing - functionality implemented in #173

**Pull request closed without merging**
