### PR TITLE
add dvchain exchange extension

### PR DESCRIPTION
**Pull request by ztnark**

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
Code looks good. Were you able to do the simple test using our tester project? There is a method to print exchange balance.

**Comment by ztnark** [comment]
Ran the test, got the expected result of NotYetImplementedForExchangeException. DVChain is an OTC exchange, balances are not held on the exchange itself.

**Comment by rpanak-generalbytes** [comment]
Return zero rather than throwing an exception. Otherwise, the user's transaction with the ATM will fail.

**Comment by ztnark** [comment]
Done. But now getting an exception on getDepositAddress. What should I have that return?

**Comment by rpanak-generalbytes** [comment]
Can you post the exception stack trace?

**Comment by ztnark** [comment]
Sure

```Crypto Balance: 0 BTC
Exception in thread "main" java.lang.NullPointerException
        at com.generalbytes.batm.server.extensions.extra.bitcoin.exchanges.XChangeExchange.getDepositAddress(XChangeExchange.java:319)
        at com.generalbytes.batm.server.extensions.test.Tester.getExchangeBalance(Tester.java:503)
        at com.generalbytes.batm.server.extensions.test.Tester.go(Tester.java:178)
        at com.generalbytes.batm.server.extensions.test.Tester.main(Tester.java:49)```

**Comment by ztnark** [comment]
I can return notimplimented, but don't want the tx to fail.

**Comment by rpanak-generalbytes** [comment]
Hi, try overriding the method and return null.

**Comment by ztnark** [comment]
Ok done. Result looks good:

```Crypto Currencies:
  BTC
  BCH
  ETH
  LTC
  XMR
Fiat Currencies:
  USD
Crypto Balance: 0 BTC
Deposit Address: null
```

**Comment by rpanak-generalbytes** [comment]
Looks good. We're preparing a release now so I'll merge it after we're done (hopefully later this week).

**Comment by rpanak-generalbytes** [comment]
Merged. Thx for the PR.

**Comment by ztnark** [comment]
🎉🎉🎉

**Comment by ztnark** [comment]
When do you anticipate this change to be released?

**Comment by generalbytes** [comment]
Today. Checkout release 20190319

**Pull request merged**
