### PR TITLE
[BitpandaPro] Support BTC/TRY and ETH/TRY

### PR DESCRIPTION
**Pull request by pyranja**
Bitpanda Pro launched TRY markets:

https://blog.bitpanda.com/bitpanda-pro-announces-turkish-trading-competition-and-turkish-lira-pairs/

This PR adds support for the `BTC` and `ETH` pairs.

### CODE REVIEW

**Comment by pyranja** [comment]
@generalbytes Can you review please?
Please let me know if there is any blocker.

Happy new year!

**Comment by pyranja** [comment]
@generalbytes hi can you please review this change?

Please let me know if there is any blocker and I'm happy to address concerns.

**Comment by generalbytes** [comment]
TRY is not currently set as primary market currency in server core. Please wait for TRY to be added into core.

**Comment by pyranja** [comment]
> TRY is not currently set as primary market currency in server core. Please wait for TRY to be added into core.

Thanks for getting back to me! I wasn't aware of this.

**Pull request closed without merging**
