### PR TITLE
updated directory layout 

### PR DESCRIPTION
**Pull request by xludx**
Updated the project to use the standard directory layout and modified libs folder structures so that they can also be used as a local maven repositories. Ant builds updated, no code changes.

### CODE REVIEW

**Comment by xludx** [comment]
@generalbytes 
Here's the first pull request as discussed.

**Comment by generalbytes** [comment]
1. PR contains a little bit more than just dir structure change: new jars xchange-poloniex, xchange-bittrex, and few scripts - but it is ok we will replace those jars with jars build on our environment.

2. Ant build output looks differently than before your change (library jars file names are different now in dist directory)

Is there some clever and simple way to somehow transform their names during the build to their names before your name change?

Some of the jars are used also in non public part of the server. Your change currently causes in combination with our build system to have two same jars in same lib directory with same classes.

**Comment by xludx** [comment]
1. the jars that I included are built from your XChange repository, but yes, you should propably replace the jars with your versions just to be sure. Scripts are just to make it easier to add new libs. 
2. You're talking about some other build that the api or extra modules, right? But yes, they are different since when installing jars to the local repository, they get copied to a directory structure which is {groupId}/{version} and renamed as {artifactId}-{versionname}.jar. After that, to be absolutely sure that maven uses the local jars, I installed them locally with a "-BATM" added to the real version name.

You could propably change the the jar names with an Ant task when copying them over to dist folder :), but lets not do that. I'll just revert the libs folder as it was, so nothing is changed there. I'll make a script that can I can use to create a local maven repository out of that when I want. That way there's no effect to your build systems and environments.

**Comment by generalbytes** [comment]
@xludx Thank you for the your hard and rigorous work. It is finally merged.

**Pull request merged**
