### PR TITLE
Add $PAC support

### PR DESCRIPTION
**Pull request by devfsc**
$PAC Extension support.

### CODE REVIEW

**Comment by generalbytes** [comment]
Please provide PAC coin icon graphics file also in SVG format as we plan to support SVG and PNG. Most likely in 2018Q4 we switch to SVG completely.

**Comment by devfsc** [comment]
PAC coin icon graphics file in SVG format are included now

**Comment by generalbytes** [comment]
Thank you

**Comment by devfsc** [comment]
The commits in this pull request were reverted because of an issue with the SVG file, are you reopening this pull request? or should I create another one with the updated file?

**Comment by generalbytes** [comment]
Gibhub doesn't allow to reopen this pull request. Please create new pull request with all files including fixed svg logo. We are going to release SVG support this week and we would like to have all currency SVG logos to look nice. Please take a look at other SVG logos to check proper dimensions etc.

**Pull request merged**
