### PR TITLE
cmc price fix for coins < rank 100

### PR DESCRIPTION
**Pull request by dArkjON**
Remove wrong POT & BTX Price var for cmc.
Add limit=0 to cmc api also a debug log.

### CODE REVIEW

**Comment by sidhujag** [comment]
Please see #57 I've fixed it properly

**Comment by generalbytes** [comment]
Please resolve conflict.

**Comment by dArkjON** [comment]
@generalbytes 
Hey Guys all conflicts are resolved now. After running the new files on a test Server i get a price for pot also btx now. Also remove the debug output.

**Comment by dArkjON** [comment]
@rpanak-generalbytes :wave: 
Please take a look in this to close the price issue in #48 for coin under coin rank 100, thanks.

**Comment by rpanak-generalbytes** [comment]
@dArkjON Thanks for the PR.  As there are a lot of calls towards CMC, so I don't want to remove the limit the way that you did. It'd make the responses substantially bigger for everyone.
If you are willing to see this through, I can suggest multiple possible solutions for coins with rank 100+:

1) Implementing the V2 API (https://coinmarketcap.com/api/) for CMC and querying only a specific coin. You have to identify the coin by CMC "id" (see https://api.coinmarketcap.com/v2/listings/). You can include the mappings from coin symbol to CMC id in the CoinmarketcapRateSource class.

2) Using V1 API an querying for a specific coin - similar to how #57 tried to do it (from the point of CMC API usage). BUT, you have to pass the coin name as the parameter (i.e. Bitcoin instead of BTC). You can have a statically initialized map that can convert from the supported coin symbol to the CMC name for that coin (this is similar to the CMC ids from previous point).

No 1) is probably better way to go as CMC API v1 will get deprecated this year.

As for the XML fix - thanks for spotting this, we somehow missed it.

**Comment by rpanak-generalbytes** [comment]
The maps can have entries just for the handful of currently supported currencies.

**Comment by rpanak-generalbytes** [comment]
This has been resolved by @sidhujag implementing CMC v2 API in #62.

The other small fixes already present on master.

**Comment by rpanak-generalbytes** [comment]
Closing

**Pull request closed without merging**
