### PR TITLE
Linda Integration

### PR DESCRIPTION
**Pull request by BraapAround**

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
Also, please make sure the code is compilable.

**Comment by NerdyUser** [comment]
@rpanak-generalbytes Thank you for your reply. 
Please review the provided commits.

**Comment by rpanak-generalbytes** [comment]
PR looks good. I merged another PR before yours, so there are merge conflicts now. Please resolve them.

While not required for the merge, consider committing an SVG version of the logo as well (if available). We are planning to start using SVG versions in the future.

**Comment by NerdyUser** [comment]
Thank you @rpanak-generalbytes, merge conflict has been solved & merged. 
I have requested an SVG file for the coin logo, will add it when I have it.

**Comment by rpanak-generalbytes** [comment]
@NerdyUser Do you want to merge this PR and later create a new one for the SVG or would you rather wait with this one for the SVG?

**Comment by NerdyUser** [comment]
Yeah @rpanak-generalbytes merge it, will make new pull request for the SVG logo 👍

**Pull request merged**
