### PR TITLE
added support for stable usd (usds)

### PR DESCRIPTION
**Pull request by markusait**
This PR adds support for Stable USD [website](stably.io) [etherscan](https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe)

I was not sure if adding RateDiscription Functionality is necessary so I left it out. Looking forward to making any changes if necessary

### CODE REVIEW

**Comment by generalbytes** [comment]
.svg file contains bitmap. That is not allowed. Please fix that.

**Comment by rpanak-generalbytes** [comment]
@markusait You should add at least a rate source for the coin. You can implement a new one, or extend one that's already implemented and can provide rate for your coin (see coinmarketcap, coinpaprika, coingecko, etc.)

**Comment by markusait** [comment]
Thanks for the reply. I updated the svg picture it does not pixelate on zoom but please let me know if it is acceptable. For the rate source, I am still unsure about how to implement it. I would like to use coinmarketcap as the price source but the code for this is in the dash folder and not in the ethereum folder `server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/dash/sources/coinmarketcap`
Should I copy it over there or just add usds there as the other tokens did. Alternatively, I would add it in a similar fashion [like EURS ](https://github.com/GENERALBYTESCOM/batm_public/pull/234/commits/50826a6c899eb6461a1697b0377109fc8c41abee)

**Comment by rpanak-generalbytes** [comment]
SVG: please no embedded bitmaps. Just proper vector graphics.

rate source: your change in the XML is ok. Don't copy the CMC code, just edit the java file and add USDS where appropriate. As you can see, it offers rates for more coins than just DASH, so the location doesn't matter.

**Comment by rpanak-generalbytes** [comment]
Also, I wouldn't stop at CoinMarketCap, as users need to pay for the API calls they make. Coinpaprika and Coingecko are free AFAIK. However, I don't know whether they support USDS.

**Comment by markusait** [comment]
Ok I uploaded a svg with paths instead of bitmap and added rate support for Coinmarketcap and Coingecko. Could you tell me if this is fine? Please, note that changes are not tested, though.

**Comment by rpanak-generalbytes** [comment]
Looks ok, but you should test preferably on BATM or at least via CAS crypto-settings tests (we don't have the resources to test every altcoin that gets implemented). Are you able to do that?

**Comment by markusait** [comment]
Hi thanks for approving! 
`./gradlew build` with gradle worked fine but 
`cp server_extensions_extra/build/libs/batm_server_extensions_extra.jar /batm/app/master/extensions/`
throws: cp: cannot create regular file '/batm/app/master/extensions/': No such file or directory

When running
`./server_extensions_test/build/install/server_extensions_test/bin/server_extensions_test -a list-exchanges     
` It throws Error: Missing -j argument.
which jar file should I point it to to test USDS?

**Comment by rpanak-generalbytes** [comment]
- the cp error: that path points to CAS installation. If it doesn't exist, you probably don't have CAS (i.e. the server) installed.
- missing -j argument: point it to the JAR created by Gradle (i.e. batm_server_extensions_extra.jar)

**Comment by markusait** [comment]
Ok thank you I got it to work using Inteliji and auto gradle build.
Now when I run the test 
` ./server_extensions_test/build/install/server_extensions_test/bin/server_extensions_test -a list-ratesources -j server_extensions_extra/build/libs/batm_server_extensions_extra.jar  -n=coingecko -p=USDS`
it just returns a list of the sources. How can I run the correct test?

**Comment by rpanak-generalbytes** [comment]
The `-a list-ratestources` parameter specifies the action to take. When you run in without any parameters, it shows the commandline syntax and other possible actions.

**Comment by markusait** [comment]
Ok I dont get the Syntax `./server_extensions_test/build/install/server_extensions_test/bin/server_extensions_test -a list-ratesources -j server_extensions_extra/build/libs/batm_server_extensions_extra.jar -n coingecko -p USDS:USD` is just returning the list again. What am I doing wrong?

**Comment by rpanak-generalbytes** [comment]
You are telling it to list the rate sources (`-a list-ratesources`), so it lists the rate sources :). Specify a different action (`-a` parameter). The possible actions are listed when running without parameters.

**Comment by markusait** [comment]
Ok I figure it out. Test with coingecko is working now for USDS.  You should maybe consider putting examples of how to test in the README I think it makes it more intuitive. The command was ` ./server_extensions_test/build/install/server_extensions_test/bin/server_extensions_test -a get-rates -j server_extensions_extra/build/libs/batm_server_extensions_extra.jar -n coingecko -p USD
` 
There was an error because `StableUSD` was uppercase so I had to convert it to lower case(see the last commit). You may want to investigate if
            
             String` crypto = CRYPTOCURRENCIES.get(cryptoCurrency).toLowerCase();

makes sense in `com/generalbytes/batm/server/extensions/extra/bitcoin/sources/coingecko/CoinGeckoRateSource.java` since this is already done with the fiat currencies as well.
Please let me know if that is fine and we can merge now.

**Comment by rpanak-generalbytes** [comment]
Thanks for making the effort and testing. I can merge it now.

**Comment by markusait** [comment]
Thanks for merging! I was wondering when I will be able to test the integration live and buy some USDS over a BATM ATM in Portland?

**Comment by rpanak-generalbytes** [comment]
Well, the next release should have the changes already. It's going to happen either this or next week. Afterwards, you'll need to persuade the operator of your favorite Portland BATM to update and enable USDS in settings. :)

**Pull request merged**
