### PR TITLE
Update Groestlcoin (new icon, addresses, segwit, rate sources)

### PR DESCRIPTION
**Pull request by HashEngineering**
This PR will update the Groestlcoin extension for the following items:

1.  The Icon is replaced with SVG and PNG files meeting the requirements
2.  Addresses are extended to allow for multisig and segwit and for the Groestl hash which is used as a checksum.
3.  Exchange rate sources are updated to refer to existing sources such as CoinGecko and CoinMarketCap.

On 2.) to support the Groestl hash, which is used as the checksum on addresses, one dependency was added to server_extensions_api along with two classes (Base58Groestl and Groestl).  Base58Groestl is derived from Base58 and to reuse code from Base58, I made one of its methods protected.  Would a better way to do this be to take these additions to `com.generalbytes.batm.server.coinutil` and put them in the `com.generalbytes.batm.server.extensions.extra.groestlcoin` package?

### CODE REVIEW

**Comment by gruve-p** [comment]
@generalbytes Is this PR acceptable or do we need to make changes?

**Comment by HashEngineering** [comment]
@generalbytes This PR is to update the GRS extension as it has several errors.

**Comment by gruve-p** [comment]
@generalbytes Current GRS implementation is non working. This PR corrects it.

**Comment by HashEngineering** [comment]
If there are no plans to support the GRS crypto-currency, we could also make a PR to remove the currently broken Groestlcoin code from this repo.

**Comment by generalbytes** [comment]
Can you please correct this PR not to contain dependency on de.sfuhrm:saphir-hash-core? We would like to avoid it for security concerns.

**Comment by HashEngineering** [comment]
Yes, `de.sfuhrm:saphir-hash-core` was removed.  Since that dependency was used to perform the hash function that is used to generate Groestlcoin addresses, a few source files were added under the `fr.cryptohash` package.

Additionally, some updates were made to the Groestlcoin classes to get them closer to BitcoinCash.

**Comment by generalbytes** [comment]
Merged. Thank you for your patience.

**Pull request merged**
