### PR TITLE
BATM Support for NULS coin

### PR DESCRIPTION
**Pull request by naveen7252**
This PR is to add NULS extension to BATM to support NULS coin in the atm.

Changes have been tested using tester module, attaching screenshots for the same.
getbalancefrombinance

nuls_ratesource_binance

Rate Source: NULS uses Binance as rate source
Wallet: NULS uses Binance as wallet for source of funds.

Please review the PR and suggest us any changes if required.

### CODE REVIEW

**Comment by naveen7252** [comment]
can this PR be reviewed please ?

Thanks

**Comment by naveen7252** [comment]
Hi, Can someone acknowledge this please ?

**Comment by naveen7252** [comment]
Hi, 
we have used most of the existing code of Lisk extension as we follow the same approach as Lisk.
So, you see this duplication. 

I have written separate classes instead of reusing Lisk classes because if Lisk extension is changed in future, it will impact our extension. We don't want to have this dependency with other extension.

Thanks

**Comment by naveen7252** [comment]
Hi,
can we proceed on this ? 

Thanks

**Comment by rpanak-generalbytes** [comment]
That's understandable, but why have you duplicated the Binance code?

**Comment by naveen7252** [comment]
We would want to have Binance as
1. Rate Source
2. Wallet

If we reuse Binance API code of Lisk extension, and if Lisk changes their implementation to go with different exchange/wallet and removes Binance API related code, then it impacts our extension. So, just to have no dependency with other extension, we have duplicated the Binance API code in our extension.

If this can be done as below: 
Please let us know if you have common package where we can move this code (Binance api related) to, so that all other extensions who wants to use that api, can reuse that code.
common code base for different APIs.

Thanks

**Comment by rpanak-generalbytes** [comment]
First of all, we wouldn't merge a PR that would degrade functionality for a different coin without a valid reason. So you needn't worry about that.

Duplicating code is an antipattern and it would make maintaining the repo a nightmare. Just take a look at CoinmarketcapRateSource. It currently supports ~26 coins (very easily extendable to support any of the additional ~2k coins they list). Having 26 (or 2k) independent copies of the code is obviously nonsense.

There's no need to move to code to a package explicitly for shared code. The rest of the repository doesn't follow this convention anyway. You can safely use the code from its original package.

**Comment by naveen7252** [comment]
alright, thanks for the assurance. I will make a change to use existing code and send you the new PR.

**Comment by rpanak-generalbytes** [comment]
Let me know when it's ready to be reviewed again.

**Comment by naveen7252** [comment]
Hi,
I have reused binance api code.

For any new Coin to use binance for rate source and wallet, following changes needs to be done:

1.Rate Source: New coin can just use BinanceRateSource.java
2. Wallet: new coin wallet can extend BinanceWallet.java and override few methods as it was done like Lisk or NULS coins.

Please review the PR and let me know if anything needs be changed.

Changes have been tested for Lisk & NULS successfully.

Thanks

**Comment by naveen7252** [comment]
Changed as per the suggestion. Please review and merge the PR.

Thanks

**Comment by rpanak-generalbytes** [comment]
Looks good. Thanks for the changes.
We're preparing a release from master. I'll merge it later (hopefully later this week).

**Comment by naveen7252** [comment]
Thanks for merging the PR. Please let us know once it is deployed.

**Comment by rpanak-generalbytes** [comment]
Merged. Thanks for the code.

**Comment by rpanak-generalbytes** [comment]
Yesterday's release (20190319) contains your changes.

**Comment by naveen7252** [comment]
Thanks for the deployment..

**Pull request merged**
