### PR TITLE
Added EFL support

### PR DESCRIPTION
**Pull request by AmazingDreams**

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
@AmazingDreams Please fix the conflicts. Note that CMC rate source has been reworked to support v2 CMC API.

**Comment by AmazingDreams** [comment]
@rpanak-generalbytes I just fixed the conflicts

**Comment by AmazingDreams** [comment]
@rpanak-generalbytes I'm not sure whether this is the best way to do this but I was informed that there is no exchange support for EFL. I couldn't find anything on exchanges within this repository myself so I was wonderwing how we can add exchange support. Thanks.

**Comment by rpanak-generalbytes** [comment]
@AmazingDreams according to https://coinmarketcap.com/currencies/e-gulden/#markets, there's Bittrex and Cryptopia support. You'd have to implement one of those exchanges. You can take a look at `BitfinexExchange` or `ItBitExchange` for inspiration.
Now the interface (`fiatCurrencyToUse` parameter of `IExchange::purchaseCoins` method) suggests you should use crypto/fiat conversion, but in reality you don't have to. You can ignore the parameter and just purchase the required amount of coins for (in your case) BTC instead of let's say USD.

**Pull request merged**
