### PR TITLE
Added Groestlcoin support

### PR DESCRIPTION
**Pull request by nuggetbram**
Compiles on my vps, but I'm not too sure how it runs as i don't have access to the server itself. Seems pretty functional though :)

### CODE REVIEW

**Comment by b00lean** [comment]
Why did you remove NLG support from batm-extensions.xml?

**Comment by martijnw** [comment]
? I haven't removed anything. Guldencoin wasn't working so might as well be
removed.

**Comment by nuggetbram** [comment]
Sorry about that, it was completely unintentional. I thought I copied & pasted it and then changed, but obviously I forgot to paste it!

**Comment by b00lean** [comment]
Please fix the problem

**Comment by nuggetbram** [comment]
Updated.

**Pull request merged**
