### PR TITLE
updates xchange to current release (4.3.14)

### PR DESCRIPTION
**Pull request by ztnark**

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
@ztnark,
The repo is no buildable after applying your changes. Unfortunately, it's not easy for us to upgrade to the newest version of XChange library. Because of transitive dependencies, we'll have many newer library versions and thus many version conflicts to resolve. Validating the resolutions (beyond just successful compilation) to make sure we don't break something takes some time. I'm afraid this is something we (GB) have to do internally.

If you are really in need of the newer version, I'd recommend identifying the features you actually need and backporting where possible. Often the backport is very easy - you just extend the original implementation class and override some methods with code copied from the newer version. We'll eventually upgrade the library but I can't give you any timeframe, unfortunately, and I don't want to delay your implementations indefinitely. Let us know whether the backport is an option for you.

**Comment by ztnark** [comment]
If I backport the features I need, how can I get them in to the master branch?

**Comment by rpanak-generalbytes** [comment]
With the newer XChange version, you'd commit code that uses some class from the library, e.g. `FooExchange e = new FooExchange();`. With the backport, you use `FooExchangeBackport e = new FooExchangeBackport();` while having `FooExchangeBackport` extend `FooExchange` and overriding the stuff you need to update with code from the newer version. FooExchangeBackport.java will be part of your PR.

**Comment by rpanak-generalbytes** [comment]
Also, you should mark the backport class with `@Deprecated` annotation with a message suggesting removal after upgrading XChange to a version newer than X.

**Comment by ztnark** [comment]
I've applied our changes on top of XChange 4.2.3. Would it be possible to use that updated version of the package?

**Comment by rpanak-generalbytes** [comment]
Have you changed the XChange lib itself? We're already using 4.2.3 and the idea was to have the backport part of our repo. If you followed my guidance and your changes don't break anything, it should be fine.

Just show us the diff (create a new PR, amend this one or send a link to the commit/branch) and I'll be able to give you more feedback.

**Comment by ztnark** [comment]
Here's the commit we made to the XChange master: https://github.com/knowm/XChange/commit/486b2f58caf7de77e5765edf9566f9aff4e94dc4

These are the only changes we need from the new version. These are the same changes I've applied on top of 4.2.3 locally.

**Comment by rpanak-generalbytes** [comment]
If you can make those changes part of our repo, then it should be fine. I've had a quick look and it seems possible. However, be aware that we won't be changing the XChange dependency as part of your PR, i.e. you have to commit the changes to our codebase (as opposed to patching the XChange lib v4.2.3). I think you can proceed and add the changes to this PR.

**Comment by ztnark** [comment]
I've opened a new pull request with the backport: https://github.com/GENERALBYTESCOM/batm_public/pull/160

**Pull request closed without merging**
