### PR TITLE
Add exchange Bitpanda Pro

### PR DESCRIPTION
**Pull request by pyranja**
Hi!

I'm working on integrating [Bitpanda Pro](https://exchange.bitpanda.com/) as an exchange and rate source. Unfortunately Bitpanda Pro is not yet supported in XChange, therefore I'm implementing `IExchangeAdvanced` and `IRateSourceAdvanced` based on existing extensions.

~~This PR is work in progress currently:~~
- [x] rate source implementation
- [x] exchange implementation
- [x] use rate limiter
- [x] remove unused api models

### CODE REVIEW

**Comment by pyranja** [comment]
I've implemented all functionality and consider this ready to be reviewed now.

**Comment by pvyhnal-generalbytes** [comment]
Please add batm-extensions.xml entry

**Comment by generalbytes** [comment]
Smarter would be to implement XChange support first and then use it in this repo. XChange library is use also by many other projects including trading bots.

**Comment by pyranja** [comment]
> Please add batm-extensions.xml entries for both the exchange and the ratesource

Added it.

> Smarter would be to implement XChange support first and then use it in this repo. XChange library is use also by many other projects including trading bots.

We are interested in adding support for Bitpanda Pro to XChange too.
Unfortunately there are time and resource constraints that prevent it at this time.
The current exchange and rate source implementation is very similar to the generic XChange adapter - I believe that we can switch at a later point in time.

**Comment by 1Crazymoney** [comment]
love learning from these emails

**Pull request merged**
