### PR TITLE
add resulting effective limit to IRemainingLimit

### PR DESCRIPTION
**Pull request by pvyhnal-generalbytes**

### CODE REVIEW

**Comment by makarid** [comment]
Hello, is this resulting effective limit the solution to the issue: #478

**Comment by pvyhnal-generalbytes** [comment]
> Hello, is this resulting effective limit the solution to the issue: #478 ? Thanks

yes

**Comment by makarid** [comment]
Thanks

**Comment by generalbytes** [comment]
Fixed in server release 20210127+

**Pull request merged**
