### PR TITLE
Cryptomat Integration

### PR DESCRIPTION
**Pull request by mmaisu**

### CODE REVIEW

**Review by generalbytes — CHANGES_REQUESTED** [review]
CryptXWalletTest.java from PR.

**Comment by mmaisu** [comment]
> CryptXWalletTest.java from PR.

Tests work on my side can you specify the problem?

**Comment by generalbytes** [comment]
Our source code should contain classes like that. Codebase needs to be clean and not contain classes that work only in someone's test environment. Leave class on your workstation do not make it part of the PR.

**Comment by mmaisu** [comment]
> Our source code should contain classes like that. Codebase needs to be clean and not contain classes that work only in someone's test environment. Leave class on your workstation do not make it part of the PR.

Remove this test from your reposittory

**Review by mmaisu — COMMENTED** [review]
Everything Looks Fine

**Review by generalbytes — APPROVED** [review]

**Pull request merged**
