### PR TITLE
add startcoin currency

### PR DESCRIPTION
**Pull request by startjoinadmin**

### CODE REVIEW

**Comment by generalbytes** [comment]
Please fix several things before we can merge your changes:
1. You are using ICurrencies.ICG which is currency code of different crypto currency. Please add your currency code into ICurrencies.java and use it.
2. Your commit is missing batm-extensions.xml changes.
3. Your commit is missing cryptocurrency png logo
Rest seems to be more or less OK.

**Comment by startjoinadmin** [comment]
Hi, we have made the changes - let me know if it's alright?
Cheers.

**Comment by generalbytes** [comment]
You are not quite there yet:
1. You forgot to commit file start.png
2.  Please fix method isStartcoinAddressValid in StartcoinAddressValidator.java - i doubt that you addresses start with 'I'.

The rest seems to be fine.

**Comment by startjoinadmin** [comment]
Hi - We have tried re-adding the start.png... All icons are in ​*server_extensions_extra/build*​ path, but this path is added to github ignore list.

We think that's why we can’t commit it?

**Comment by generalbytes** [comment]
You are doing simple copy&paste development and you seem to get lost even in that.
Are you a programmer?

PNG files should be here:
https://github.com/GENERALBYTESCOM/batm_public/tree/master/server_extensions_extra/res

**Comment by startjoinadmin** [comment]
Hi - apologies, our newest developer is quite new to this. Png has been added. Thanks.

**Pull request merged**
