### PR TITLE
Update Linda Logo

### PR DESCRIPTION
**Pull request by NerdyUser**
Updated .png logo to .svg (transparant)

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
Thanks.

**Comment by NerdyUser** [comment]
FYI @rpanak-generalbytes is your commit correct? I uploaded an SVG file, not an PNG file.

**Comment by rpanak-generalbytes** [comment]
We don't support SVGs yet, so there has to be the PNG file specified. I corrected your change in XML, but I didn't notice you removed the PNG file. Will correct that on master.

Thanks for the heads-up.

**Comment by rpanak-generalbytes** [comment]
@NerdyUser I had to remove the SVG file from master. If you look at the contents, you'll see it is only a hi-res PNG in embedded in SVG format. Can you provide a proper vector-graphics SVG?

**Pull request merged**
