### PR TITLE
add support for BTCP

### PR DESCRIPTION
**Pull request by Pega88**
Please use this PR https://github.com/BTCPrivate/BitcoinPrivate/pull/159 instead of master, as master has no support for ACCOUNTS, which this PR requires.

### CODE REVIEW

**Comment by rpanak-generalbytes** [comment]
@Pega88 I put this on hold untill there is a BTCP release with accounts support. There are already some merge conflicts and I guess there will be more untill BTCPrivate/BitcoinPrivate#159 gets merged and released. I'd suggest to wait till that happens and then resolve the conflicts. Let us know afterwards.

**Comment by Pega88** [comment]
Thanks for your reply @rpanak-generalbytes . Will address conflicts.

On the accounts: Currently, Bitcoin Private has no plans to incorporate accounts into the master branch. We specifically enabled it for General Bytes in the form of a Pull Request, so you could use that commit to build a GeneralBytes-specific daemon with accounts enabled. It was never intended to merge the PR.

Would you be willing to build from that commit rather than from master, as long as we maintain it / merge upstream? 

If you cannot work with the separate commit, I'll address this in the team and try to convince team to effectively merge the PR.

Thanks for your time,

Niels.

**Comment by rpanak-generalbytes** [comment]
@Pega88 The issue is that once we merge your PR, some customers running their own server will try the integration, installing the BTCP daemon (which they will get from upstream) and the accounts feature won't be present. Our support is quite busy as it is so we'd like to avoid any unnecessary confusion for the customers.

While we can work with a particular commit/PR/branch, it's unfeasible to support this for customers with their own server installs (too many coins for the manpower).

If you need this for your GB BATM network ASAP, you can always build your own extensions jar and replace the one found in our server install. Unfortunately, you have to do this (apply patch, build jar, replace original jar) after each server upgrade.

**Comment by Pega88** [comment]
@rpanak-generalbytes makes perfect sense. We'll do the merge of the PR and a new release. I already solved the current conflicts. Will let you know once the account feature is merged.

**Comment by Pega88** [comment]
Hi @rpanak-generalbytes , accounts have been enabled and the release has been built.  Currently there is not merge conflict.

https://github.com/BTCPrivate/BitcoinPrivate/releases

let me know what the next steps are.

**Comment by rpanak-generalbytes** [comment]
Ok, I'll go over the code and merge it (if no problems are found) once the new merge window opens.

**Comment by rpanak-generalbytes** [comment]
Merged. Thx for the commits.

I'd suggest adding exchange support. It'll improve the real world usability significantly.

**Pull request merged**
