### PR TITLE
Maven build

### PR DESCRIPTION
**Pull request by xludx**
@generalbytes @b00lean

This pull request contains:
- Maven build
- changes to BitcoinAverage mostly to allow it to be easily mocked and tested
- fixed the IBitcoinAverage @Path's 
- added tests which mock the BitcoinAverage api's and make sure correct price is being fetched
- modified the Ant build to also run the tests

### CODE REVIEW

**Comment by xludx** [comment]
@b00lean @generalbytes could you merge this?

**Comment by kewde** [comment]
@b00lean @generalbytes 
Why is this not moving forward?

**Comment by generalbytes** [comment]
Please remove bitcoin average changes from your pull request. Also, we are going to remove bitcoinaverage form repository completely as their free service is not usable any more due to call rate limiting.

**Comment by xludx** [comment]
removed bitcoinaverage

**Comment by xludx** [comment]
I'm closing these since sdc is dead soon.

**Pull request closed without merging**
