### PR TITLE
DASH and WDC support for BATM

### PR DESCRIPTION
**Pull request by rrunner7**
Hi,

this merge request contain the support for DASH and WDC buy option in BATM server. Please check and merge with master branch.

The condition to work withe the currencies are:
1. full wallet node for the currency.
2. enable TLS1.1 and TLS1.2 in the batm-manage file in start command:
cmd_start() function behind "java" in both daemons add  -Dhttps.protocols=TLSv1.1,TLSv1.2
This is a error in the JAVA 7 which has the two protocol disabled in ubuntu 14.04 (do not know if all distributions are affected).

BR,
Martin

### CODE REVIEW

**Comment by generalbytes** [comment]
Please remove  -Dhttps.protocols=TLSv1.1,TLSv1.2 parameter dependency as suggested in email.

**Comment by generalbytes** [comment]
Please resolve conflicts and fix the TLS stuff as suggested via email.

**Comment by generalbytes** [comment]
Please resolve the conflict

**Comment by rrunner7** [comment]
Conflict should be resolved. The 2 new currencies  should be added to the ICurrencies.java file

**Comment by generalbytes** [comment]
No the conflict is still there.

**Comment by rrunner7** [comment]
Ok, removed but it will not work if the ICurrencies.java do not contain the two new currencies.

**Pull request merged**
