### PR TITLE
Added ShadowCash support, maven build and tests

### PR DESCRIPTION
**Pull request by xludx**
Changes:
- Added multi module Maven project to build the project and manage dependencies, refactored the project to use maven directory structure (src -> src/main/java). Of course, you can still use Ant if you like.
- Updated some dependencies to newer versions, for example xchange from 4.0.0-SNAPSHOT to 4.0.0 (to be able to add xchange-bittrex and xchange-poloniex dependencies), which also required few changes in the existing code. 
- Added local maven repository for BitcoinJSONRPCClient and shadowcashd-client since they are not available on any public repositories.
- Added Bittrex, Poloniex and FixPrice rate sources.
- Added shadowcashd wallet support. 
- Created tests for ShadowCash rate sources and wallet, added api-mocks for Bittrex, Poloniex, Bitcoinaverage and Shadowcashd.

### CODE REVIEW

**Comment by kewde** [comment]
You did quite the job here :+1: 
The new ratesources are handy for all cryptocurrencies.

**Comment by xludx** [comment]
Added support for ShadowCash paper wallet.

**Comment by xludx** [comment]
merged the latest changes from master

**Comment by kewde** [comment]
@generalbytes if there are any problems, let us know. We'll get it done ASAP.

**Comment by kewde** [comment]
@b00lean @generalbytes can someone atleast give us pointers as to why this pull request is being ignored?

**Comment by generalbytes** [comment]
I cannot merge your changes because:
1. We don't want to have maven. We need to know exactly which jars are going to be in our release and audited built by us. By using maven you never know what ends in final release which is security risk if you consider that we deploy this code into every atm server.
2. We have to use XChange 4.0.1  - because it contains some of the fixes (Bitfinex and Ethereum related) - your code is based on 4.0.0
3. This PR is over-engineered. You made so many changes into one pull request. Making it one big hell of a change 236 files changed for one cryptocurrency. I'm not willing to merge it in this state.

**Comment by kewde** [comment]
Thank you for the reply @generalbytes!

We'll revert the Maven code, and move over to XChange 4.0.1 to comply with your requests.

The PR is quite extensive, that I agree with.  But there is a misconception about how many files were actually changed, about 80% of the files github marks as changed in fact didn't change at all. It claims 'the filename was changed' but that hasn't happened either, really weird.

Options to get prices from Poloniex and Bittrex have been added which made it bigger than the usual coin.

**Comment by xludx** [comment]
@generalbytes @b00lean Thanks for your comments. 

When I wrote this code, you're code was based on some older version of XChange 4.0.0-SNAPSHOT, which was still using the older package name. To add SDC support, I needed to use and add the xchange-bittrex and xchange-poloniex dependencies and after fetching those, I noticed that the SNAPSHOT version of XChange had allready switched to using the new package name. I could not add the needed dependencies then without upgrading XChange to the latest RELEASE version. I can understand your current need for the 4.0.1-SNAPSHOT dependency, but could you tell us the commit id on which your SNAPSHOT build is based on, so that we know which version of those dependencies to use? I'm guessing commit 4ce1643c1c2130e0af9320d5b748525f06ca7728?

I somehow figured, that for some reasons, you don't want to use Maven. That's fine, I've made sure that I didn't break your Ant build and Maven is not a requirement. However, claiming you cannot know which dependencies Maven includes is not correct, see the local-maven-repository that I created just for that purpose. If, for security purposes, you need to build all your dependencies yourselves, then that would be easy way you could add those dependencies to your project.

I don't know what exactly is "over-engineered" here? If you're referring to the number of changed files, then that's mostly because of switching to the standard directory layout. I've only touched the files outside of shadowcash extension when I needed to upgrade to use the new XChange package naming. You've done that now, so my changes can be discarded. I can also change the standard directory layout back to what it was, if you seriously think thats a bad thing?

**Comment by generalbytes** [comment]
Hi @xludx 
I'm aware that you made significant time+energy investment into the code. Don't take me wrong, I value and thank you for that.

Current ATM server builds use XChange 4.0.1 and are/will_be based on https://github.com/GENERALBYTESCOM/XChange
I introduced this repo in latest release. This way you will always know what XChange version you code against to. If you will need to increase version number let me know and i will update https://github.com/GENERALBYTESCOM/XChange to required version.

Our previous versions of xchange libraries contained also our patches that exchanges didn't permit us to publish publicly. But I noticed that over the time these features have been added into the Xchange by other developers. So now we finally can use pure xchange.


ATM server already contains quite a lot of dependencies.
Bitcoinj, xchange, ethereumj etc. libraries that evolve quite quickly and incorporate major changes without warning.  It is a challenging job to keep ATM server stable and up-to-date as each of our customers uses different exchange in different way.
That is also one of the reasons why i try to be conservative when it comes to having latest versions of libraries/code.

If you can somehow streamline your pull request to contain reasonable number of changes that i can actually manually read, check and have confidence that nothing more or less will breaks, than i will be happy to merge it. including the optional maven build.

**Comment by xludx** [comment]
@generalbytes @b00lean

Ok, how about if I'd split all this in three different pull requests?

1. **Update the project to use the standard directory layout**. This would be mainly to allow separation of project code and test code. I would also like to modify the libs folder structure, so that at the same time it would work also as a local maven repository and there wouldn't be a need to store those libs twice. This would mean moving libs/artifactId.jar to: libs/{groupId}/{version}/{artifactId}.jar. I would not touch any source code, just update the directory layout and the Ant build.

2. **Add maven build**. And on code side I would at least modify BitcoinAverageRateSource, so that I can mock the service with WireMock and fix IBitcoinAverage, and so that I can make sure the tests run without problems. I can't remember if I modified something else, but I'd try to put all non-SDC changes here, so you can easily check the changes related to the existing code. No SDC related code added yet. 

3. **All SDC related code changes**. RateSources, shadowcashd support, paperwallet, tests, etc. I would also modify the current code to get rid of the custom shadowcash client and some other not-needed libraries like Lombok to keep the amount of new dependencies to minimum. 

How would that sound?

**Comment by generalbytes** [comment]
@xludx I agree. Lets start with Nr. "1."

**Comment by xludx** [comment]
I'm closing these since sdc is dead soon.

**Pull request closed without merging**
